Added check for poolsize
fission/fission pull request #1809
Opened 2020-10-05 14:36 UTC by Divya063

Closes #1720

2020-10-07 06:55 UTC, therahulbhati commented
@Divya063  default size of the pool is 3 as mentioned here https://github.com/fission/fission/blob/master/pkg/fission-cli/flag/flag.go#L149. Instead of setting pool to 1 explicitly, a warning with taking default value 3 should work.
CC @vishal-biyani

2020-10-07 06:57 UTC, therahulbhati reviewed
Apart from requested changes, LGTM

2020-10-13 09:43 UTC, therahulbhati approved these changes

2020-10-13 09:56 UTC, therahulbhati requested changes

2020-10-13 09:56 UTC, therahulbhati commented on pkg/fission-cli/cmd/environment/create.go
> +			poolsize = input.Int(flagkey.EnvPoolsize)
Can you make the logic more concise because if the flag is not set you will get default value 3, at line 121

2021-06-07 09:45 UTC, vishal-biyani commented
Closing in favour of https://github.com/fission/fission/pull/1837

2021-06-07 09:45 UTC, closed without merging