#1719 Enhanced list env and func cli commands
fission/fission pull request #1821
Opened 2020-10-10 10:15 UTC by sbawaskar

2020-10-10 16:23 UTC, sbawaskar commented
@vishal-biyani , please review.

2020-10-19 11:05 UTC, therahulbhati requested changes
Apart from suggested changes

2020-10-28 16:01 UTC, vishal-biyani requested changes

2020-10-29 10:19 UTC, vishal-biyani commented
Hey @sbawaskar Can you please take a look at review comments when you get a chance

2021-01-19 18:06 UTC, vishal-biyani commented
Hey @sbawaskar I am closing this PR for lack of activity but please feel free to chat and re-open if you think we should collaborate on this!

2021-01-19 18:06 UTC, closed without merging