Fix golint warnings for publisher package
fission/fission pull request #1822
Opened 2020-10-10 16:12 UTC by ShajithaMohammed

As part of #58

2020-10-19 11:31 UTC, therahulbhati requested changes

2020-10-19 11:31 UTC, therahulbhati commented on pkg/publisher/publisher.go
> +	// name in a queue-based publisher such as NATS.
The comment on the Publisher interface can be written as:
```
// Publisher interface wraps the Publish method that publishes message and headers
// 
// Publish an request to a "target".  Target's meaning depends on the	
// publisher: it's a URL in the case of a webhook publisher, or a queue	
// name in a queue-based publisher such as NATS.
```

2020-10-19 11:31 UTC, therahulbhati commented on pkg/publisher/webhookPublisher.go
> +// MakeWebhookPublisher triggers a publish request to the given baseUrl with 10 maximum retries in case of error
```suggestion
// MakeWebhookPublisher creates a WebhookPublisher object for the given baseUrl
```

2020-10-19 11:31 UTC, therahulbhati commented on pkg/publisher/webhookPublisher.go
> +// Publish sends a request to the target with given payload with a defined retries in case of error
```suggestion
// Publish sends a request to the target with payload having given body and headers
```

2020-10-22 08:12 UTC, therahulbhati approved these changes

2020-10-22 08:13 UTC, therahulbhati approved these changes
LGTM

2020-10-27 15:49 UTC, merged

2020-10-27 15:49 UTC, vishal-biyani commented
Thanks for the PR @ShajithaMohammed

2020-11-10 15:32 UTC, chetanpdeshmukh commented
Hello @ShajithaMohammed ,
Thanks again for the PR!

Thank you for contributing to Fission project. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdhxtWL5N2PU7MYC2IRRAzYw-CrG9QtsYNvkiiOPVEQj8i51w/viewform?usp=sf_link), so we can send you the well deserved awesome swags :)

Team Fission