Add websocket test
fission/fission pull request #2053
Opened 2021-06-03 07:47 UTC by RealHarshThakur

Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>

2021-06-03 08:44 UTC, RealHarshThakur commented on test/tests/websocket/specs/env-nodejs.yaml
> +    image: harshthakur/node-websocket:1
TODO: Update this to fission repo when we push the images

2021-06-09 14:19 UTC, sanketsudake requested changes

2021-06-09 14:19 UTC, sanketsudake commented on test/tests/websocket/test_ws.sh
> +cd ./test/tests/websocket/ && go run main.go
Please get dir of script and then do run based on script path, same test_mqtrigger.sh

2021-06-10 06:32 UTC, sanketsudake approved these changes

2021-06-10 06:57 UTC, merged