Use Kubernetes Client instead of Controller APIs from CLI
fission/fission pull request #2605
Opened 2022-11-04 12:23 UTC by neha-Gupta1

## Description
Use the Kubernetes and Fission Client from CLI instead of Controller API. 
This removes port-forwarding for controller 

## Which issue(s) this PR fixes:

Fixes #

## Testing
All the CLI actions should work similarly. 
NOTE: We will now throw an error if the resource creation request was made for Namespace which is not present. This is to come inline with Kubernetes behaviour. 
## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [ ] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [ ] My changes follow contributing guidelines of Fission.
- [ ] I have signed all of my commits.

2022-11-05 06:38 UTC, sanketsudake requested changes

2022-11-05 06:38 UTC, sanketsudake commented on pkg/fission-cli/cmd/canaryconfig/list.go
>  	if input.Bool(flagkey.AllNamespaces) {
Please rewrite this as.

```
if input.Bool(flagkey.AllNamespaces) {
     opts.namespace = metav1.NamespaceAll
}
canaryCfgs, err := opts.Client().FissionClientSet.CoreV1().CanaryConfigs(opts.namespace).List(input.Context(), metav1.ListOptions{})
```

2022-11-05 06:38 UTC, sanketsudake commented on pkg/fission-cli/cmd/environment/list.go
>  	if input.Bool(flagkey.AllNamespaces) {
please check above comment about all namespace. Please correct all
`if input.Bool(flagkey.AllNamespaces)` conditions.

2022-11-05 06:38 UTC, sanketsudake commented on pkg/fission-cli/cmd/function/test.go
> +func printPodLogs(client cmd.Client, fnMeta *metav1.ObjectMeta) error {
Please pass CLI context here.

2022-11-05 06:38 UTC, sanketsudake commented on pkg/fission-cli/cmd/function/test.go
> +	// else {
remove commented code.

2022-11-05 06:38 UTC, sanketsudake commented on pkg/fission-cli/cmd/package/get.go
> +		// readCloser, err := pkgutil.DownloadStoragesvcURL(opts.Client().DefaultClientset, archive.URL)
Please remove unwanted code.

2022-11-07 03:47 UTC, neha-Gupta1 commented on pkg/fission-cli/cmd/canaryconfig/list.go
>  	if input.Bool(flagkey.AllNamespaces) {
Done

2022-11-07 12:56 UTC, sanketsudake approved these changes

2022-11-07 16:12 UTC, merged