[WIP] : Create role and role binding required for service account
fission/fission pull request #2667
Opened 2022-12-10 14:12 UTC by shubham-bansal96

## Description

## Which issue(s) this PR fixes:

Fixes #

## Testing

## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [ ] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [ ] My changes follow contributing guidelines of Fission.
- [ ] I have signed all of my commits.

2022-12-12 04:44 UTC, sanketsudake requested changes

2022-12-12 04:44 UTC, sanketsudake commented on charts/fission-all/values.yaml
> +## enableCreateSA enables fission to create service account, roles and rolebinding for builder and fetcher.
Please add section under executor called `serviceAccountCheck`

it should have to two fields
```
serviceAccountCheck:
      # true/false
      enabled: true
      # in minutes
      interval: 30 
```

2022-12-12 04:44 UTC, sanketsudake commented on charts/fission-all/templates/buildermgr/deployment.yaml
> +        - name: CREATE_SA
Please name env variable

`SERVICEACCOUNT_CHECK_ENABLED`

2022-12-12 04:44 UTC, sanketsudake commented on charts/fission-all/templates/buildermgr/deployment.yaml
> +        - name: SA_INTERVAL
Please name env variable

`SERVICEACCOUNT_CHECK_INTERVAL`

2022-12-12 11:32 UTC, sanketsudake requested changes

2022-12-12 11:32 UTC, sanketsudake commented on charts/fission-all/templates/buildermgr/deployment.yaml
> +          value: {{ .Release.Name | quote }}
Please remove trailing space.

2022-12-12 11:32 UTC, sanketsudake commented on charts/fission-all/templates/executor/deployment.yaml
> +        {{- if .Values.executor.serviceAccountCheck.enable }}
`.enable` -> `.enabled`

2022-12-12 11:32 UTC, sanketsudake commented on charts/fission-all/values.yaml
> +    enable: false
`enabled` to have consistency across helm values.

2022-12-13 12:11 UTC, sanketsudake requested changes

2022-12-13 12:11 UTC, sanketsudake commented on charts/fission-all/templates/_fission-kubernetes-roles.tpl
> +- apiGroups:
Please enable these permissions only if service account check is enabled.

2022-12-13 14:52 UTC, sanketsudake approved these changes

2022-12-13 15:01 UTC, sanketsudake requested changes

2022-12-13 15:01 UTC, sanketsudake commented
Fixes https://github.com/fission/fission/issues/759

2022-12-13 15:42 UTC, shubham-bansal96 commented on pkg/utils/serviceaccount.go
> +	roleBinding, err := client.RbacV1().RoleBindings(sa.Namespace).Create(context.TODO(), roleBindingObj, metav1.CreateOptions{})
done

2022-12-14 03:36 UTC, merged