handle concurrent requests
fission/fission pull request #2737
Opened 2023-03-09 10:48 UTC by pranoyk

## Description
The idea is to keep a track of number of pods in specialization and to figure out the virtual capacity

### Terminology
- Capacity
   - Actual capacity - specialized pod * rpp
   - Virtual Capacity - (specialized pod + pods in specialization state) * rpp
  
### Approach
- update a counter in pool cache when a specialization starts
- if concurrent requests comes in wait for the pod under specialization to finish
   - keep a track of incoming requests and wait them if specialization is under progress (wait only if virtual capacity is more then incoming number of requests)
- if the incoming number of requests is more then the virtual capacity then start a new specialization and repeat the above process
- if the number of concurrent requests is more than the total capacity (concurrency * rpp) return error

Fixes #1939 

## Test scenarios
- rpp 60, concurrency 5
- rpp 1, concurrency 500
- rpp 5, concurrency 5

2023-03-20 09:10 UTC, sanketsudake requested changes

2023-03-20 09:10 UTC, sanketsudake commented on pkg/executor/executortype/newdeploy/newdeploymgr.go
> +func (deploy *NewDeploy) SpecializationStart(context.Context, *fv1.Function) {}
Please remove this

2023-03-21 13:27 UTC, sanketsudake commented on pkg/apis/core/v1/types.go
> +		return 500
Please define constants above and use them here.

DefaultConcurrency and DefaultRequestPerPod

2023-03-21 13:28 UTC, sanketsudake commented on pkg/executor/executortype/container/containermgr.go
> +func (caaf *Container) GetFuncSvcFromPoolCache(ctx context.Context, fn *fv1.Function) (*fscache.FuncSvc, error) {
Remove method from interface as well.

2023-03-21 13:29 UTC, sanketsudake commented on pkg/executor/executortype/newdeploy/newdeploymgr.go
> +func (deploy *NewDeploy) GetFuncSvcFromPoolCache(ctx context.Context, fn *fv1.Function) (*fscache.FuncSvc, error) {
Please remove method.

2023-03-21 13:31 UTC, sanketsudake commented on pkg/executor/fscache/poolcache.go
> +				if capacity > 0 {
We are not checking capacity > 1 ?

2023-03-21 13:32 UTC, sanketsudake commented on pkg/executor/fscache/poolcache.go
> +							popped.svcChannel <- req.value
Close channel once value is sent ?

2023-03-21 13:37 UTC, sanketsudake commented on pkg/executor/fscache/poolcache.go
> +						if popped.ctx.Err() == nil {
If requests has timed out we can drop request. And consider additional in place ?
eg. top of queue has 4 timed out request then we have capacity of 4 then we should drop first 4 and consider next 4 ? 

Also its quite possible that we can run into race condition. Just need to ensure we are not working on stale capacity value.

2023-03-23 13:42 UTC, sanketsudake commented on pkg/executor/fscache/poolcache.go
> +					if popped != nil {
Invert condition
```
if  popped == nil {
      break
}
... rest of code
```
for better readability.

2023-03-23 13:42 UTC, sanketsudake commented on pkg/executor/fscache/poolcache.go
> +	specializationStart
We can remove these and related code if not needed anymore.

2023-03-30 14:49 UTC, merged

2024-05-19 16:20 UTC, LyKos4 commented
When I set concurrency 1 or rpp 1 and try to run a  function more than 1 pods are created for that run, why does this happen?
Same for yolo true

Doesn't yolo true of rpp 1 mean that a function run should be done by a new single pod, meaning 1 pod per function run?